
apiVersion: apps/v1
kind: Deployment # Set up the deployement kind
metadata:
  name: product-service-deployment1 # Name for the deployement
  labels:
    app: product-service
spec:
  replicas: 1 # Number of clones that we want
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: productrepo.azurecr.io/productservice:v1 
          ports:
            - containerPort: 3000 
--- 
apiVersion: v1
kind: Service 
metadata:
  name: product-service-loadbalancer-service
  labels:
    app: product-service
spec:
  type: LoadBalancer 
  selector:
    app: product-service
  ports:
    - port: 5000
      targetPort: 3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service-deployment1 
  labels:
    app: delivery-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: productrepo.azurecr.io/deliveryservice:v1  
          ports:
            - containerPort: 6500 
--- 
apiVersion: v1
kind: Service
metadata:
  name: delivery-service-loadbalancer-service
  labels:
    app: delivery-service
spec:
  type: LoadBalancer 
  selector:
    app: delivery-service
  ports:
    - port: 5001
      targetPort: 6500
---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: order-service-deployment1 
  labels:
    app: order-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: productrepo.azurecr.io/orderservice:v1 
          ports:
            - containerPort: 6501
--- 
apiVersion: v1
kind: Service 
metadata:
  name: order-service-loadbalancer-service
  labels:
    app: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - port: 5002
      targetPort: 6501
---

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: customer-service-deployment1 
  labels:
    app: customer-service
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: productrepo.azurecr.io/customerservice:v1   
          ports:
            - containerPort: 5500 
--- 
apiVersion: v1
kind: Service 
metadata:
  name: customer-service-loadbalancer-service
  labels:
    app: customer-service
spec:
  type: LoadBalancerg
  selector:
    app: customer-service
  ports:
    - port: 5003
      targetPort: 5500
